/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cbrojas.view;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author brand
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    PanConversorMonedas panMonedas = new PanConversorMonedas();
    PanConversorAngulos panAngulos = new PanConversorAngulos();
    PanConversorTemperatura panTemperatura = new PanConversorTemperatura();

    public FrmPrincipal() {
        initComponents();
        
    }

    private void showPanel(JPanel panel12) {
        panel12.setSize(800, 600);
        panel12.setLocation(0, 0);

        panDesktop.removeAll();
        panDesktop.repaint();

        panDesktop.add(panel12);
        panDesktop.revalidate();
        panDesktop.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConvertirMonedas = new javax.swing.JButton();
        btnConvertirTemperatura = new javax.swing.JButton();
        ConvertirAngulos = new javax.swing.JButton();
        panDesktop = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConvertirMonedas.setText("Conversor de Monedas");
        btnConvertirMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirMonedasActionPerformed(evt);
            }
        });
        jPanel1.add(btnConvertirMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 206, 41));

        btnConvertirTemperatura.setText("Conversor de Temperaturas");
        btnConvertirTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirTemperaturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnConvertirTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 206, 41));

        ConvertirAngulos.setText("Conversor de Ángulos");
        ConvertirAngulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirAngulosActionPerformed(evt);
            }
        });
        jPanel1.add(ConvertirAngulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 206, 41));

        javax.swing.GroupLayout panDesktopLayout = new javax.swing.GroupLayout(panDesktop);
        panDesktop.setLayout(panDesktopLayout);
        panDesktopLayout.setHorizontalGroup(
            panDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panDesktopLayout.setVerticalGroup(
            panDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(panDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 800, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirMonedasActionPerformed

        try {
            showPanel(panMonedas);
        } catch (Exception e) {
            System.out.println("\n\n***********ERROR*********MONEDA***********");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnConvertirMonedasActionPerformed

    private void btnConvertirTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirTemperaturaActionPerformed
        try {
            showPanel(panTemperatura);
        } catch (Exception e) {
            System.out.println("\n\n***********ERROR************TEMPERATURA********");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnConvertirTemperaturaActionPerformed

    private void ConvertirAngulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirAngulosActionPerformed
        try {
            showPanel(panAngulos);
        } catch (Exception e) {
            System.out.println("\n\n***********ERROR*************ANGULOS*******");
            e.printStackTrace();
        }
    }//GEN-LAST:event_ConvertirAngulosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConvertirAngulos;
    private javax.swing.JButton btnConvertirMonedas;
    private javax.swing.JButton btnConvertirTemperatura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panDesktop;
    // End of variables declaration//GEN-END:variables
}
