/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cbrojas.view;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author cbrojas
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    PanConversorMonedas panMonedas = new PanConversorMonedas();
    PanConversorAngulos panAngulos = new PanConversorAngulos();
    PanConversorTemperatura panTemperatura = new PanConversorTemperatura();
    PanPortada panPortada= new PanPortada();
    

    public FrmPrincipal() {
        initComponents();
        showPanel(panPortada);

    }

    private void showPanel(JPanel panel) {
        panel.setSize(660, 500);
        panel.setLocation(0, 0);

        panDesktop.removeAll();
        panDesktop.repaint();

        panDesktop.add(panel);
        panDesktop.revalidate();
        panDesktop.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConvertirMonedas = new javax.swing.JButton();
        ConvertirAngulos = new javax.swing.JButton();
        panDesktop = new javax.swing.JPanel();
        btnConvertirTemperatura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONVERSOR DE UNIDADES");
        setMaximumSize(new java.awt.Dimension(660, 580));
        setMinimumSize(new java.awt.Dimension(660, 580));
        setPreferredSize(new java.awt.Dimension(660, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConvertirMonedas.setBackground(new java.awt.Color(164, 198, 233));
        btnConvertirMonedas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConvertirMonedas.setForeground(new java.awt.Color(31, 58, 147));
        btnConvertirMonedas.setText("Conversor de Monedas");
        btnConvertirMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirMonedasActionPerformed(evt);
            }
        });
        jPanel1.add(btnConvertirMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 41));

        ConvertirAngulos.setBackground(new java.awt.Color(164, 198, 233));
        ConvertirAngulos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ConvertirAngulos.setForeground(new java.awt.Color(31, 58, 147));
        ConvertirAngulos.setText("Conversor de Ángulos");
        ConvertirAngulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirAngulosActionPerformed(evt);
            }
        });
        jPanel1.add(ConvertirAngulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 190, 41));

        panDesktop.setBackground(new java.awt.Color(237, 237, 237));
        panDesktop.setPreferredSize(new java.awt.Dimension(660, 500));

        javax.swing.GroupLayout panDesktopLayout = new javax.swing.GroupLayout(panDesktop);
        panDesktop.setLayout(panDesktopLayout);
        panDesktopLayout.setHorizontalGroup(
            panDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        panDesktopLayout.setVerticalGroup(
            panDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(panDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 660, 500));

        btnConvertirTemperatura.setBackground(new java.awt.Color(164, 198, 233));
        btnConvertirTemperatura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConvertirTemperatura.setForeground(new java.awt.Color(31, 58, 147));
        btnConvertirTemperatura.setText("Conversor de Temperaturas");
        btnConvertirTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirTemperaturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnConvertirTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 190, 41));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirMonedasActionPerformed
        showPanel(panMonedas);
    }//GEN-LAST:event_btnConvertirMonedasActionPerformed

    private void btnConvertirTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirTemperaturaActionPerformed
        showPanel(panTemperatura);
    }//GEN-LAST:event_btnConvertirTemperaturaActionPerformed

    private void ConvertirAngulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirAngulosActionPerformed
        showPanel(panAngulos);
    }//GEN-LAST:event_ConvertirAngulosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConvertirAngulos;
    private javax.swing.JButton btnConvertirMonedas;
    private javax.swing.JButton btnConvertirTemperatura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panDesktop;
    // End of variables declaration//GEN-END:variables
}
