/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cbrojas.view;

import com.cbrojas.model.Angulos;
import com.cbrojas.model.MethodKeyEvent;
import com.cbrojas.model.Temperaturas;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

/**
 *
 * @author cbrojas
 */
public class PanConversorTemperatura extends javax.swing.JPanel {

    /**
     * Creates new form PanConversorTemperatura
     */
    Temperaturas temperatura;
    
    private DecimalFormat formateador;
    private DecimalFormatSymbols simbolo;
    
    public PanConversorTemperatura() {
        initComponents();
        temperatura = new Temperaturas();
        
        simbolo = new DecimalFormatSymbols();
        simbolo.setDecimalSeparator('.');

        formateador = new DecimalFormat("#.##", simbolo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRankine = new javax.swing.JTextField();
        txtCelsius = new javax.swing.JTextField();
        txtFahrenheit = new javax.swing.JTextField();
        txtKelvin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(660, 500));
        setMinimumSize(new java.awt.Dimension(660, 500));
        setPreferredSize(new java.awt.Dimension(660, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(237, 237, 237));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(660, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 58, 147));
        jLabel1.setText("DE TEMPERATURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 58, 147));
        jLabel2.setText("Rankine:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 58, 147));
        jLabel3.setText("Celsius:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 58, 147));
        jLabel4.setText("Fahrenheit:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 58, 147));
        jLabel5.setText("Kelvin:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        txtRankine.setBackground(new java.awt.Color(216, 216, 216));
        txtRankine.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtRankine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRankineKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRankineKeyTyped(evt);
            }
        });
        jPanel1.add(txtRankine, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 210, 40));

        txtCelsius.setBackground(new java.awt.Color(216, 216, 216));
        txtCelsius.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtCelsius.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCelsiusKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelsiusKeyTyped(evt);
            }
        });
        jPanel1.add(txtCelsius, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 210, 40));

        txtFahrenheit.setBackground(new java.awt.Color(216, 216, 216));
        txtFahrenheit.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFahrenheit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFahrenheitKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFahrenheitKeyTyped(evt);
            }
        });
        jPanel1.add(txtFahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 210, 40));

        txtKelvin.setBackground(new java.awt.Color(216, 216, 216));
        txtKelvin.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtKelvin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKelvinKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKelvinKeyTyped(evt);
            }
        });
        jPanel1.add(txtKelvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 210, 40));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(31, 58, 147));
        jLabel6.setText("CONVERSOR DE UNIDADES");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCelsiusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelsiusKeyTyped
        if (MethodKeyEvent.evaluarTeclas(evt.getKeyChar(), txtCelsius.getText()))
            evt.consume();
    }//GEN-LAST:event_txtCelsiusKeyTyped

    private void txtCelsiusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelsiusKeyReleased
        double num = MethodKeyEvent.validarCadenaCajaDeTexto(txtCelsius.getText()) ? 0 : Double.parseDouble(txtCelsius.getText());

        if (MethodKeyEvent.evaluarTeclas(evt.getKeyChar(), num)) {
            temperatura.setCelsius(num);
            
            txtFahrenheit.setText(formateador.format(temperatura.getFahrenheit()));            
            txtKelvin.setText(formateador.format(temperatura.getKelvin()));
            txtRankine.setText(formateador.format(temperatura.getRankine()));

        }
    }//GEN-LAST:event_txtCelsiusKeyReleased

    private void txtKelvinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKelvinKeyTyped
        if (MethodKeyEvent.evaluarTeclas(evt.getKeyChar(), txtKelvin.getText()))
            evt.consume();
    }//GEN-LAST:event_txtKelvinKeyTyped

    private void txtKelvinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKelvinKeyReleased
        double num = MethodKeyEvent.validarCadenaCajaDeTexto(txtKelvin.getText()) ? 0 : Double.parseDouble(txtKelvin.getText());

        if (MethodKeyEvent.evaluarTeclas(evt.getKeyChar(), num)) {
            temperatura.setKelvin(num);
            
            txtCelsius.setText(formateador.format(temperatura.getCelsius()));
            txtFahrenheit.setText(formateador.format(temperatura.getFahrenheit()));
            txtRankine.setText(formateador.format(temperatura.getRankine()));

        }
    }//GEN-LAST:event_txtKelvinKeyReleased

    private void txtRankineKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRankineKeyTyped
        if (MethodKeyEvent.evaluarTeclas(evt.getKeyChar(), txtRankine.getText()))
            evt.consume();
    }//GEN-LAST:event_txtRankineKeyTyped

    private void txtRankineKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRankineKeyReleased
        double num = MethodKeyEvent.validarCadenaCajaDeTexto(txtRankine.getText()) ? 0 : Double.parseDouble(txtRankine.getText());

        if (MethodKeyEvent.evaluarTeclas(evt.getKeyChar(), num)) {
            temperatura.setRankine(num);
            
            txtCelsius.setText(formateador.format(temperatura.getCelsius()));
            txtFahrenheit.setText(formateador.format(temperatura.getFahrenheit()));            
            txtKelvin.setText(formateador.format(temperatura.getKelvin()));

        }
    }//GEN-LAST:event_txtRankineKeyReleased

    private void txtFahrenheitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFahrenheitKeyReleased
        double num = MethodKeyEvent.validarCadenaCajaDeTexto(txtFahrenheit.getText()) ? 0 : Double.parseDouble(txtFahrenheit.getText());

        if (MethodKeyEvent.evaluarTeclas(evt.getKeyChar(), num)) {
            temperatura.setFahrenheit(num);
            
            txtCelsius.setText(formateador.format(temperatura.getCelsius()));            
            txtKelvin.setText(formateador.format(temperatura.getKelvin()));
            txtRankine.setText(formateador.format(temperatura.getRankine()));

        }
    }//GEN-LAST:event_txtFahrenheitKeyReleased

    private void txtFahrenheitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFahrenheitKeyTyped
        if (MethodKeyEvent.evaluarTeclas(evt.getKeyChar(), txtFahrenheit.getText()))
            evt.consume();
    }//GEN-LAST:event_txtFahrenheitKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCelsius;
    private javax.swing.JTextField txtFahrenheit;
    private javax.swing.JTextField txtKelvin;
    private javax.swing.JTextField txtRankine;
    // End of variables declaration//GEN-END:variables
}
